### ISSUE TITLE
Additional trained models, perhaps a centralised repo?

### ISSUE THREAD

**Issue by coreshock** [graphdeco-inria/gaussian-splatting#106]
The example models are mind-blowing, but are there any additional resources with trained models, except for the 14 gigs archive?

**Comment by Snosixtyboo** [comment]
Hi,

this is not planned due to the logistics and usage rights. I'm afraid if we create an upload location where anybody can upload, we cannot moderate the content there without significant effort. We don't really have much more pre-processed models ourselves, but the community has been showing off some cool things on Twitter and LinkedIn, so if there is motivation to start an unofficial repo, please feel free to do so and we can then mention it on the Github!

Best,
Bernhard
