### ISSUE TITLE
How to start remote render server after training

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#11]
SIBR_remoteGaussian_app can be used to connect to training process on remote machine, but how can I use the remote machine to render remotely after rendering?

**Comment by Snosixtyboo** [comment]
Hi,

sorry, we never considered this as a use case because the purpose of the method is real-time rendering, and the remote renderer is unoptimized, so using it impacts rendering performance a lot. We always envisioned trained models to be run locally with high performance. You can render training and test sets remotely after training using ```render.py```, but no interactive rendering.

Best,
Bernhard

**Comment by HrsPythonix** [comment]
> 

Got it

**Comment by ihorizons2022** [comment]
> 

hello, i can use SIBR_remoteGaussian_app to connect to the remote training server, but cannot find the right path to model path, even i use --path to indicate the right path.

could you please give me some clues or how can you do it right?

thanks

**Comment by shumash** [comment]
Hi, we had the same problem and put together a very simple interactive viewer in a jupyter notebook. This allows viewing remote checkpoints using the default render function -- just run `jupyter lab` on the remote machine and connect to the browser with ssh port forwarding.

See here the full end-to-end example: 
[github.com/shumash/gaussian-splatting/blob/mshugrina/interactive/interactive.ipynb](https://github.com/shumash/gaussian-splatting/blob/mshugrina/interactive/interactive.ipynb)
