### ISSUE TITLE
Is it possible to obtain a foreground mask during rendering?

### ISSUE THREAD

**Issue by sunshineatnoon** [graphdeco-inria/gaussian-splatting#139]
Hi, Thanks for open-sourcing this wonderful project. I'm trying to use the representation for an object. Is it possible to render a RGBA image instead of RGB image as in the [PointRenderer in Pytorch3D](https://pytorch3d.org/tutorials/render_colored_points)?

**Comment by Snosixtyboo** [comment]
You can, but you would have to modify the Python and CUDA code yourself. All that should be needed (for the forward pass at least) is to change the output tensor, and in CUDA switch the indexing to 4 floats per pixel instead of 3 and write out the variable ```T``` in the alpha channel in addition to the RGB.

**Comment by sunshineatnoon** [comment]
Hi, thanks for the response. Is it convenient for you to point me to the relevant code?

**Comment by Orig1n** [comment]
> Hi, thanks for the response. Is it convenient for you to point me to the relevant code?

Hi, I aslo want to obtain the foreground mask during during rendering. Have you found out how to do that?
