### ISSUE TITLE
discussions about environment.yml

### ISSUE THREAD

**Issue by Yang-Xijie** [graphdeco-inria/gaussian-splatting#143]
This is more like a note, instead of an issue.

- `torchaudio` is an unnecessary package that can be removed from `environment.yml`.
- `cudatoolkit` will be automatically installed when installing PyTorch. So `cudatoolkit` can be removed from `environment.yml`.
- Installing PyTorch using conda might cause error like "libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11" when installing submodules (diff-gaussian-rasterization and simple-knn).
    - Users can manually run `pip install nvidia-cublas-cu11` and `pip install -e submodules/diff-gaussian-rasterization && pip install -e submodules/simple-knn` after creating the new conda environment to install submodules.
    - Installing PyTorch using pip (`pip install torch torchvision`) will automatically install `nvidia-cublas-cu11`.
- Using packages with the latest version meets no error when running `train.py` and `render.py`. Will it be better to remove the version restrictions in `environment.yml`?
    - Tested with python 3.11.4, pip 23.2.1, torch 2.0.1, torchvision 0.15.2, tqdm 4.66.1, plyfile 1.0.1.

And the equivalent commands to create the environment are:

```sh
conda create -y -n gs python pip
conda activate gs

pip install torch torchvision
pip install -e submodules/diff-gaussian-rasterization
pip install -e submodules/simple-knn
pip install tqdm plyfile
```

**Comment by Snosixtyboo** [comment]
Hi,

this are all good points. However, we chose the environment as we did for the sake of reproducibility. Given that this is the code for a scientific paper, we want to ensure that other researchers can reproduce our results (PSNR, SSIM, LPIPS scores): that is our key motivation for releasing the code. The scripts may run with newer/older versions, but we cannot foresee changes in behavior due to version changes, especially if it's major versions. That is why we created the environment the way we did.

**Comment by Yang-Xijie** [comment]
Thanks for your reply! I'm just getting started in scientific research so it is a valuable suggestion for me!

**Comment by StevenS963** [comment]
That is very very helpful! You are a lifesaver! @Yang-Xijie  
@Snosixtyboo I understand you’re focused on ensuring reproducibility, which is commendable. However, rather than simply stating that the SDK must be compatible, it’s crucial to facilitate smooth code execution for users. If the environment setup is problematic, users could spend a significant amount of time resolving these issues. Instead of closing this issue, it would be beneficial to emphasize the details of this issue in your README to help guide users more effectively.
