### ISSUE TITLE
Remote visualization on windows, training in remote docker?

### ISSUE THREAD

**Issue by sergiobdrl** [graphdeco-inria/gaussian-splatting#149]
Hi,

I am succesfully training in a remote docker container (running Ubuntu 22.04) and the 6009 port is being forwarded to localhost:6009. 
Is it possible to use the Windows binary to see my training progress? When I try this, the app opens and then crashes.

**Comment by Snosixtyboo** [comment]
Hi,

we didn't try it in Docker, unfortunately. It worked for us in WSL (training on WSL Ubuntu and attaching a from the underlying Windows). IF you do this, you may need to provide the additional ```-s``` flag to the remote viewer! The server will share with the client the filename for the scene to load. But if the server is using Windows and sends a path like ```/f/data/scene```, then Windows won't be able to deal with this. So you could in this case add ```-s F:/data/scene``` so that the Windows client can find the scene.

**Comment by Snosixtyboo** [comment]
Closed due to inactivity

**Comment by litaws** [comment]
> Hi,
> 
> I am succesfully training in a remote docker container (running Ubuntu 22.04) and the 6009 port is being forwarded to localhost:6009. Is it possible to use the Windows binary to see my training progress? When I try this, the app opens and then crashes.

Would you mind sharing the `Dockerfile` you used?
