### ISSUE TITLE
How to use fast culling in render.py

### ISSUE THREAD

**Issue by HrsPythonix** [graphdeco-inria/gaussian-splatting#22]
I saw `fast culling` option in SIBR_gaussianViewer_app.exe, it can speed up 2X the FPS in my scene (50fps -> 100fps), I wonder if I can also use this option in render.py?

**Comment by Snosixtyboo** [comment]
> I saw `fast culling` option in SIBR_gaussianViewer_app.exe, it can speed up 2X the FPS in my scene (50fps -> 100fps), I wonder if I can also use this option in render.py?

Hi,
I don't think it's straightforward, you would need to provide a tensor on the python side big enough to hold 2 * ```num_points``` integers and then pass that through, all the way to become the last parameter of CudaRasterizer::Rasterizer::forward in C++.  If you try this, there's a couple of caveats:
1) It probably does nothing to the speed of render.py which is governed by writing files to disk and slower python code
2) I wouldn't expect this change to mess with backward, but it MIGHT because it's untested, so after doing this, if training doesn't work we probably wouldn't know how to help.

Hth,
Bernhard
