### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#25]
```
Tensorboard not available: not logging progress [13/07 01:10:31]
Reading camera 56/56 [13/07 01:10:31]
Loading Training Cameras [13/07 01:10:31]
Loading Test Cameras [13/07 01:11:08]
Number of points at initialisation :  26558 [13/07 01:11:08]
Training progress:  23%|█████████████████████▏                                                                     | 7000/30000 [09:00<34:06, 11.24it/s, Loss=0.0516592]Traceback (most recent call last):
  File "train.py", line 204, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "train.py", line 99, in training
    training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, render, (pipe, background))
  File "train.py", line 162, in training_report
    images = torch.cat((images, image.unsqueeze(0)), dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2588 but got size 2589 for tensor number 1 in the list.
Training progress:  23%|█████████████████████▏                                                                     | 7000/30000 [09:01<29:39, 12.93it/s, Loss=0.0516592]
```
Images are 56 of around 3451 x 5178, I tried running with the auto 1.6k scaling and also with -r 2 and still get same type of error

**Comment by Snosixtyboo** [comment]
Hi,

it would seem that some of your images have different resolutions? Afaict this shouldn't happen if the dataset has been undistorted via COLMAP. We haven't done testing on it, but it should still be possible to just run the code with images of different sizes. The part that will fail is only the evaluation, so you could either skip it (--test_iterations -1) or modify the corresponding code slightly so that it can compute avg PSNR and L1 on images of different sizes (e.g., compute it per image, then add to a sum and divide at the end). If that works we could take it in as a pull request, but just to be clear, we didn't do qualified testing on image data sets with different resolutions.

Hth,
​​​​​​​Bernhard

**Comment by henrypearce4D** [comment]
Hi Bernhard, this is from a multicamera rig but all cameras and lenses on this set are the same. We have other datasets to try that have varied w x h (portrait/landscape) orientations so these settings will be useful.

Just checking the undistorted images from colmap and the sizes are varied, in colmap I can try choosing the option that all images share the same exif.

I presume this has happened because these images have a mask applied (comped over), so I had to re-inject the the exif data, perhaps colmap doesnt like this.

On this subject of masks, how does the train.py deal with masks? I see that it handles nerf synthetic with RGBA (mask in alpha) but what about images from colmap? can you have a mask folder that is used as part of  convert.py process and the masks also be exported as undistorted?

**Comment by Snosixtyboo** [comment]
> Hi Bernhard, this is from a multicamera rig but all cameras and lenses on this set are the same. We have other datasets to try that have varied w x h (portrait/landscape) orientations so these settings will be useful.
> 
> Just checking the undistorted images from colmap and the sizes are varied, in colmap I can try choosing the option that all images share the same exif.
> 
> I presume this has happened because these images have a mask applied (comped over), so I had to re-inject the the exif data, perhaps colmap doesnt like this.
> 
> On this subject of masks, how does the train.py deal with masks? I see that it handles nerf synthetic with RGBA (mask in alpha) but what about images from colmap? can you have a mask folder that is used as part of convert.py process and the masks also be exported as undistorted?

Hi, unfortunately we have no functionality to work with separate RGB and mask images. But if you have such a dataset, creating a combined RGBA dataset with the masks in the alpha channel could be somewhat quickly achieved with e.g. ImageMagick and a script that composites them. You could try extending the convert.py to do this on demand since it already uses ImageMagick, but we ourselves won't prioritize making this change right now.

Hth,
Bernhard
