### ISSUE TITLE
a quesion about stereo information in PC

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#336]
the input is point-cloud, generated by 'colmap SfM'.

very 'STRONG STEREO' information in PC as input, right? so ...

others algrithms (e.g NeRF ...) just used 'POSE ONLY' from colmap, ...

if we append PC as a part of inputs to NeRF* (by sampling, or other ways) , then ...

**Comment by yuedajiong** [comment]
title modified

**Comment by Snosixtyboo** [comment]
@yuedajiong That sounds like a great goal! And would be a really revolutionary technique if it works out!

I see you have raised a number of other issues. Some of them are ideas on what could be improved about the approach. This is really interesting, but the Github issues are meant to inform us, the developers, whether the code works as ORIGINALLY DESCRIBED in the paper. Of course the method and implementation could always be better! But I would kindly suggest to instead put such messages in boards meant for wider discussions (e.g., Reddit) so that we have a chance to keep track of bugs and other blocking issues.

**Comment by yuedajiong** [comment]
sorry.
please close these disscussions.
yes, most of them, not issues.

sorry.

:-(

**Comment by yuedajiong** [comment]
I will not submit this type of pseudo issue.   sorry.
:-)
