### ISSUE TITLE
How to parse the `geomBuffer, binningBuffer, imgBuffer`

### ISSUE THREAD

**Issue by XuyangBai** [graphdeco-inria/gaussian-splatting#34]
Hi Thanks for sharing this great work. I wondering is there any ways to parse the `geomBuffer, binningBuffer, imgBuffer` returned by `rasterize_gaussians`? I tried but didn't figure out a correct ways to parse those buffers.

**Comment by Snosixtyboo** [comment]
Hi,

those buffers hold temporary internal data for the rasterizer and are returned only so that PyTorch can take care of managing them (move in memory, cache) however it sees fit. The info in there is ever only parsed on the C++/CUDA side. You can dig into it from there, but it's probably not useful.

Best,
Bernhard
