### ISSUE TITLE
remote viewer cannot find the model path

### ISSUE THREAD

**Issue by ihorizons2022** [graphdeco-inria/gaussian-splatting#35]
I use SIBR remote viewer to connect to remote training server, and training server indicates the viewer is connected but the viewer app cannot find the model path, even i use --path to give the right model path in training server

could you please explain the following instructions, and that would be better if you can give me an example.

due to them running on different (virtual) machines), you may specify an override location to the viewer by using -s <source path>

Thanks

**Comment by Snosixtyboo** [comment]
Hi,

First we need to distinguish model and source path
source: where the input data lies (colmap info in sparse/0, images)
model: where the trained model is written to

When you run training, you use an input path with ```-s```, maybe 
```train.py -s F:/data/scene```

If you are on the same machine, you simply do
```./SIBR_remoteGaussian_app```

If you are on a different machine, you may instead do
```./SIBR_remoteGaussian_app --ip <IP> --port <port> -s D:/training_data/scene```
or, e.g. if the client runs in a virtual machine on the same PC, but with linux instead of windows:
```./SIBR_remoteGaussian_app -s /mnt/f/data/scene```

Using ```--path``` should be equivalent to using ```-s``` for the **VIEWERS**. You said you are passing ```--path``` to the training server? This is not expected to work. It should instead be passed to the remote viewer. 

Let me know if that solve sit for you,
best,
Bernhard

**Comment by ihorizons2022** [comment]
thank you for your reply. 
For example, A is the training server, B is the remote viewer.
On A, I run train.py -s [scene] -m [model output] --ip 0.0.0.0
if i want to launch the viewer on B , what should i do?
./SIBR_remoteGaussian_app  --ip [ip of A] -s [model output directory on A ]?

**Comment by ihorizons2022** [comment]
<img width="735" alt="image" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/121672603/9c727608-0d11-41f9-800d-343339652a52">
could I understand like this?
1. scene data [processed by colmap ] and SIBR_remoteGaussian_app should be on B
2. training server like A receive scene data from B?

**Comment by Snosixtyboo** [comment]
> thank you for your reply. For example, A is the training server, B is the remote viewer. On A, I run train.py -s [scene] -m [model output] --ip 0.0.0.0 if i want to launch the viewer on B , what should i do? ./SIBR_remoteGaussian_app --ip [ip of A] -s [model output directory on A ]?

Hi, not quite! The last line should be
```./SIBR_remoteGaussian_app --ip [ip of A] -s [path to [scene] reachable by B]```

A will send its **string** of [scene] to B. B will try to set it up (cameras, images, etc) from that path. There's multiple reasons why this may not work.

Case 1: A and B are different machines. You give ```-s F:/data``` to A. B doesn't have anything in ```F:/data```, so it can't load the file. You can e.g., make a duplicate of [scene] on B, e.g., in ```D:/data_dup``` and then use ```-s D:/data_dup``` on B. Then they both load the same scene and should be fine. Or perhaps you might store your scenes on network paths, which are reachable by both A and B, then this problem should never occur.

Case 2: A and B are the same machine, but one is a VM, the other is windows. You give ```-s /mnt/f/data``` to A. B, because it is Windows, cannot use this path format. So you pass ```-s F:/data``` to B, translating the path from linux to windows format.

Hth?

**Comment by Snosixtyboo** [comment]
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/121672603/253556545-9c727608-0d11-41f9-800d-343339652a52.png"> could I understand like this? 1. scene data [processed by colmap ] and SIBR_remoteGaussian_app should be on B 2. training server like A receive scene data from B?

Nope, B receives a **string** from A. A starts and loads a scene. If B connects, A tells B where it got the data, but only the path. It does this because scene data may be HUGE, so it won't send all of it over the network. B will try to load the data from the path that A sent. It may not be able to do this, for multiple reasons (like the ones I gave above).

**Comment by ihorizons2022** [comment]
thank you very much, I will have a try.

**Comment by Snosixtyboo** [comment]
@ihorizons2022 Any success?

**Comment by ihorizons2022** [comment]
No luck.
I put all files produced by colmap in convert.py both in A[training server] and B[viewer server].
On B,  viewer can be run, but only black screen

<img width="960" alt="1" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/121672603/70563444-44ca-4685-9c28-28fb3f9dc19a">

<img width="960" alt="捕获" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/121672603/9fd3e14a-78b0-4caf-891e-c167f155af3d">

**Comment by ihorizons2022** [comment]
I  will reset all settings and try again.
I think I make some mistakes in specific step

**Comment by penguinflys** [comment]
It looks very unintuitive to setup a source images locally, as the remote viewer is intended to be used remotely. It is somehow not very `remote`

**Comment by Snosixtyboo** [comment]
Theoretically, yes. There would need to be an initial handshake protocol that tells the remote viewer where all the cameras are and bars the user from trying to display the SfM points, because they are potentially too large to transmit as part of the handshake. That being said, having the images locally should never be required (I think!), only the cameras.bin|txt and images.bin|txt are required.

**Comment by penguinflys** [comment]
> I succeeded by specifying the output path to the -s, like this: ./SIBR_remoteGaussian_app.exe -s '\wsl$\Ubuntu-20.04\Myname\root\gaussian-splatting\output\apple001' ./SIBR_remoteGaussian_app.exe in my windows10 and \wsl$\Ubuntu-20.04 is the WSL2 path. In the repository's README, it seems to specify the input datapath like '\wsl$\Ubuntu-20.04\home/root/gaussian-splatting/data/Apple', but this will cause errors.

looks good, Maybe specifying a ssh path would also work? unluckily I cannot test it as my company has a special file accessing gate for security reason.
