### ISSUE TITLE
Why is 'spatial_lr_scale' hard coded to 5?

### ISSUE THREAD

**Issue by JonathonLuiten** [graphdeco-inria/gaussian-splatting#38]
see this line:
https://github.com/graphdeco-inria/gaussian-splatting/blob/737f75406999ff1bc2196bd107bc89caf09afe88/scene/gaussian_model.py#L87

this used to be set based on self.spatial_lr_scale = spatial_lr_scale, and thus setting it to the initial radius calculated in data preproc.

Now it is hard coded to 5.

Is this better?

**Comment by Snosixtyboo** [comment]
Hi,

yes. This was an overcomplication on our side. The gradients/learning rate should not be scaled by the size of the scene, this breaks some of the principles behind it. We discovered this when users tried much larger data sets. Going back, we found that COLMAP would always use a similar scene extent, therefore the lr_scale for most models in our evaluation was a value very close to 5. At some point, we will clean this and simply multiply the default learning rates by 5 and push after testing it.

**Comment by Snosixtyboo** [comment]
Btw @JonathonLuiten is https://github.com/graphdeco-inria/gaussian-splatting/issues/33 still an issue for you? Can we do something to address it?

**Comment by JonathonLuiten** [comment]
Does this mean that if the data was not collected with colmap, that this hard coded value could be very wrong and bad?
E.g. we should make sure to 'physically' scale any scene to a similar scale as colmap uses?

Yeah it's fine, was mostly just checking it wasn't a mistake and that it made sense. I will close that issue. Will leave this one open until question above answered.

**Comment by Snosixtyboo** [comment]
Hi,

thanks for bringing it up, we have discussed it internally and we agree that this change can appear confusing without proper explanation. We have therefore rolled it back for now and will release it later with a corresponding explanation of what this means for scene preparation in the README. I'll leave this issue open until then.

Thanks,
Bernhard

**Comment by Snosixtyboo** [comment]
Ok @JonathonLuiten  here goes, thanks for being skeptical, it was very helpful to us :)

We have implemented the following changes:
- ```scaling_lr``` was updated to a fixed value 0.005 (5 x 0.001, explanation below)
- ```position_lr_...``` is scaled with the extent of the scene.

How does this ensure adaptive behavior regardless of scene scale? In the case of position, it seems intuitive, Gaussians should move further if the scene is larger (actually it only is that simple because we use Adam, but that's for another day). For the scales, we need to remember that we encode them with a log. That means when we actually use them, we activate them with exp(). In a larger scene, the Gaussians are initialized to be larger at the start, consistent with the scale (based on the distance to the nearest neighbors). This already ensures that the rate of change in size will be relative to the actual scene size using a constant learning rate. You can experimentally confirm that exp(X + 0.1) / exp(X) = exp(aX + 0.1) / exp(aX) for any non-zero a, S. I have also attached some napkin math if you are so inclined.

![logfun](https://github.com/graphdeco-inria/gaussian-splatting/assets/40643808/c2e975bb-85c2-410a-9a22-570630568efc)

Hth!
Bernhard

**Comment by JonathonLuiten** [comment]
Hey Bernhard!

Thanks for looking at this!

From my understanding you're right that both the scales and positions are easy to scale, however the real problem here is the rotations.

I bet you, that if you took EXACTLY the same scene and just rescaled it, you'd get VASTLY different 'rotation' results (whether that matters for the kind of nerf-scenes we're optimizing is a different question), but I bet you at one end of the scale continuum they all stay at 'eye' rotation, and at the other end they all happy rotate around to wherever...

Like I said, maybe it doesn't matter too much for making volume rendering look good, but for other apps where rotation is important (e.g. estimating camera poses) this matters ALOT...

About 1 year ago I did a lot of investigations into this with @leonidk and the best we came up with at the time was just to make sure to normalize your scene before optimizing (although maybe he has more opinions).

**Comment by Snosixtyboo** [comment]
> Hey Bernhard!
> 
> Thanks for looking at this!
> 
> From my understanding you're right that both the scales and positions are easy to scale, however the real problem here is the rotations.
> 
> I bet you, that if you took EXACTLY the same scene and just rescaled it, you'd get VASTLY different 'rotation' results (whether that matters for the kind of nerf-scenes we're optimizing is a different question), but I bet you at one end of the scale continuum they all stay at 'eye' rotation, and at the other end they all happy rotate around to wherever...
> 
> Like I said, maybe it doesn't matter too much for making volume rendering look good, but for other apps where rotation is important (e.g. estimating camera poses) this matters ALOT...
> 
> About 1 year ago I did a lot of investigations into this with @leonidk and the best we came up with at the time was just to make sure to normalize your scene before optimizing (although maybe he has more opinions).

Thanks for this interesting take! We may do some experiments on this, but as far as our understanding goes currently, there's two levels of spatial discrepancies:
- gradients have different sizes due to projection (enlarge the same scene -> smaller gradients in world space)
- learning rates need to adapt to fit enlarged scenes (larger scene -> actually need to move more)

The first we basically delegate to Adam: it will change the learning rates dynamically and should be invariant to a constant scaling factor. The second is the adaptation to accommodate the larger scene with the updates. This should and does matter for translation and scaling: in a 10x larger scene, the same update should now move Gaussians 10x further. But rotations should not be increased, so right now we think that Adam should be doing the heavy lifting for us... but we can investigate :)

**Comment by leonidk** [comment]
Jono tagged me here, but I had similar results with my rendering for [Fuzzy Metaballs](https://leonidk.github.io/fuzzy-metaballs/)

Changing scene scale would change the gradients. There were basically two ways to deal with this in my work. For FMB, the actual gradients scale as `1/s` for several scene properties (translation,  means) and `s` for others (precision matrix) and some are unaffected (weights). 

- One solution is to only use Momentum (not Adam) for optimization, and then apply the appropriate scale correction to the gradients (I do this in my pose estimation example). 
- Another solution, if you prefer Adam, is to scale your scene to an appropriate, canonical scale. If your scale is too large or to small, the optimization prioritizes `translation > shape` or `shape > translation`. (I do this in my shape estimation example)
