### ISSUE TITLE
Known issues with Cuda tool kit 11.6 ?

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#45]
In the software requirements of the setup is says;

CUDA SDK 11 for PyTorch extensions (we used 11.8, known issues with 11.6)

yet in the environment.yml is says;

dependencies:
  - cudatoolkit=11.6
  
  can some one explain this please?

**Comment by Snosixtyboo** [comment]
Hi,

there's two different things. One is the full CUDA SDK, including the compiler (NVCC). We need it to build the PyTorch extensions that we wrote ourselves and that the optimizer uses. The other is the CUDA runtime that PyTorch is built against (the latest CUDA runtime that PyTorch 1.12 works with is 11.6). If you install PyTorch with CUDA with Conda, it installs a small subset of the full CUDA SDK that cannot do compilation. If you install the full 11.6 SDK and try to compile our extensions with it, it can fail because of a known issue with C++14 support in the 11.6 CUDA compilers.

Hth,
Bernhard

**Comment by henrypearce4D** [comment]
Thankyou for the detailed information
Henry

**Comment by xuyaojian123** [comment]
> Hi,
> 
> there's two different things. One is the full CUDA SDK, including the compiler (NVCC). We need it to build the PyTorch extensions that we wrote ourselves and that the optimizer uses. The other is the CUDA runtime that PyTorch is built against (the latest CUDA runtime that PyTorch 1.12 works with is 11.6). If you install PyTorch with CUDA with Conda, it installs a small subset of the full CUDA SDK that cannot do compilation. If you install the full 11.6 SDK and try to compile our extensions with it, it can fail because of a known issue with C++14 support in the 11.6 CUDA compilers.
> 
> Hth, Bernhard

If I install the full 11.8 SDK(nvcc -V output cuda11.8) and environment.yml dependencies modified cudatoolkit=11.8. Will this be successful? Thank you!
