### ISSUE TITLE
Can't clone submodules: simple-knn and SIBR_viewer

### ISSUE THREAD

**Issue by kenton0607** [graphdeco-inria/gaussian-splatting#477]
I tried to clone the repository recursively as below, 
`git clone --recursive git@github.com:graphdeco-inria/gaussian-splatting.git`
but I couldn't get simple-knn and SIBR_viewer submodules except diff-gaussian-rasterization.

I checked those whether repositories are available or not on github, but those links can't work, but I found those repositories are working when I search them directly from web browser (this was already mentioned on #446 ). What is going on them and what should I have to do to clone completely?

**Comment by yuedajiong** [comment]
Oh my god, look, there is a guy can not checkout correctly.  :-)

1.  git clone with --recursive.   try git or ssh protocols.
2.  try different ways,   on linux or on windows,   in command line or on web,  manually download zip and unzip to related folder, ...
3.  in China, due to GFW firewall,  maybe need VPN and manually download and unzip.
4.  download my zip for you.    please say thanks to me.  :-(


[GS.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13387397/GS.zip)

**Comment by henrypearce4D** [comment]
@yuedajiong second time I've seen you are rude. Please be more friendly.
