### ISSUE TITLE
Any suggestions on using lidar point clouds to initialize 3dgs to reconstruct large scenes

### ISSUE THREAD

**Issue by Bin-ze** [graphdeco-inria/gaussian-splatting#503]
I'm trying to reconstruct a relatively large indoor scene using the 3dgs algorithm, in this case using colmap can easily fail due to the large number of low texture and similar areas in the interior. So I tried exporting the point cloud and pose from polycam and from there, trained 3dgs.
It is worth noting that the point cloud obtained from polycam is about 50 times denser than using colmap and is very close to the surface of the object.
But in all current attempts, using dense pcd to initialize 3dgs cannot achieve satisfactory results. If anyone has any relevant experience, it would be greatly appreciated!

**Comment by GaoPeng97** [comment]
Hello, how was it going? I am in the same situation. I have precise point cloud of a scene, and some pictures of this scene. I am not attempting to reconstruct the scene, just wanting to dye the color of picture onto the point cloud. So that I could get a better visual representation of this scene. 

But the result is not satisfied.

**Comment by Bin-ze** [comment]
如果不是为了渲染场景，只是为了为点云染色，结果不满意只能说明图像与点云没有配准（也就是坐标系不对应，如果您认为您的点云是精确的情况下）

penk ***@***.***> 于2024年1月23日周二 16:58写道：

**Comment by pattgene** [comment]
I would like to ask about progress in your idea about applying point clouds from lidar to train 3dgs. How was it going
