### ISSUE TITLE
Failed to create sparse model.

### ISSUE THREAD

**Issue by Jiang-HB** [graphdeco-inria/gaussian-splatting#524]
Dear Authors,

I extend my gratitude for presenting such an intriguing and potent project. I have successfully attained remarkable reconstruction results using your datasets.

However, I encountered an issue while attempting to reconstruct the KITTI dataset. The error message displayed is "ERROR: failed to create sparse model." This occurred when using the KITTI sequence featured in your FQA.

I am reaching out to seek your guidance on resolving this matter. Do you have any insights or recommendations to address this specific error with the KITTI dataset?

Your assistance in overcoming this challenge would be greatly appreciated.

Thank you for your time and consideration.

Best Regards,
Haobo

**Comment by Snosixtyboo** [comment]
Hi, this seems to be a problem in the COLMAP processing, which is not maintained by us. I recommend to find out the exact colmap step and error message and then contacting COLMAP authors.

**Comment by MingyunZhu** [comment]
=> No good initial image pair found. Elapsed time: 6.288 [minutes] 
ERROR: failed to create sparse model 
ERROR:root:Mapper failed with code 256. Exiting.
I asked GPT, and it told me the problem was probably that the image files I generated in the previous step were of poor quality and not dense enough. The generated images need to be as continuous as possible and not too scattered.
A good approach is to directly extract frames using video tools. For example, extract frames every few frames, or at a higher density. Currently, I’m using 1 frame every 5 frames (fps=25 overall):
plaintext
ffmpeg -i input.mp4 -vf "setpts=0.2*PTS" input/input_%4d.jpg
This way, no errors occur. Previously, the issue was that I had taken the images manually with my phone, so they were probably not continuous.
If I use video recording instead, I’ll need a better camera for shooting.
