### ISSUE TITLE
Reducing artifacs on real scene

### ISSUE THREAD

**Issue by Bishadkoju** [graphdeco-inria/gaussian-splatting#57]
<img width="403" alt="Screenshot 2023-07-25 at 10 29 09" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/45235817/7de5fb3a-df78-4c0c-93cc-f0bb5b8f09a0">

Hi, I'm getting these types of artifacts . Does anyone know what causes it and how to reduce it ?

**Comment by grgkopanas** [comment]
When you zoom too much this is inherent to our representation, there is nothing constraining the optimisation not to do that, since there are no zoomed-in views of the subject, macroscopically this is basically creating complex texture effects. 

Unfortunately zooming in without getting this kind of effects while maintaining very sharp and detailed textures is not trivial  and is left for future work .

**Comment by Bishadkoju** [comment]
![picnicSpot](https://github.com/graphdeco-inria/gaussian-splatting/assets/45235817/3aa45832-debb-49e9-8e14-4a6d52ec8811)
![sundarichowk](https://github.com/graphdeco-inria/gaussian-splatting/assets/45235817/d994f768-e9ee-4132-b682-b92b452bd14c)

Hi, these kind of artifacts is seen at surfaces closer to the camera. On training for fewer iteration (7000) these areas appears blurred but on futher training, it takes these over-detailed textures. Is there some way to smooth it out ? The results on the regions further away from the camera are pretty decent.

**Comment by grgkopanas** [comment]
as I said:

> Unfortunately zooming in without getting this kind of effects while maintaining very sharp and detailed textures is not trivial and is left for future work .

**Comment by Bishadkoju** [comment]
Okay. Thank you :)

**Comment by s1ddok** [comment]
@grgkopanas do you think it is possible to mitigate those artifacts by providing more zoomed-in data?

**Comment by hariharan1412** [comment]
> @grgkopanas do you think it is possible to mitigate those artifacts by providing more zoomed-in data?

Did you try it? Is it working?
