### ISSUE TITLE
Backward gradient formulation mistake?

### ISSUE THREAD

**Issue by liquorleaf** [graphdeco-inria/gaussian-splatting#596]
In https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/cuda_rasterizer/backward.cu, line 550,
Update gradients w.r.t. 2D covariance (2x2 matrix, symmetric)
```c++
atomicAdd(&dL_dconic2D[global_id].y, -0.5f * gdx * d.y * dL_dG);
``` 
I draw that the second item of the conic matrx should have a twice coefficient. Why this is not
```c++
atomicAdd(&dL_dconic2D[global_id].y, -gdx * d.y * dL_dG);
``` 
?

**Comment by Ruyi-Zha** [comment]
It seems that 0.5 is compensated [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L210). `2*dL_dconic.y` makes `2*0.5=1`.
```
dL_da = denom2inv * (-c * c * dL_dconic.x + 2 * b * c * dL_dconic.y + (denom - a * c) * dL_dconic.z);
dL_dc = denom2inv * (-a * a * dL_dconic.z + 2 * a * b * dL_dconic.y + (denom - a * c) * dL_dconic.x);
dL_db = denom2inv * 2 * (b * c * dL_dconic.x - (denom + 2 * b * b) * dL_dconic.y + a * b * dL_dconic.z);
```

**Comment by liquorleaf** [comment]
> It seems that 0.5 is compensated [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L210). `2*dL_dconic.y` makes `2*0.5=1`.
> 
> ```
> dL_da = denom2inv * (-c * c * dL_dconic.x + 2 * b * c * dL_dconic.y + (denom - a * c) * dL_dconic.z);
> dL_dc = denom2inv * (-a * a * dL_dconic.z + 2 * a * b * dL_dconic.y + (denom - a * c) * dL_dconic.x);
> dL_db = denom2inv * 2 * (b * c * dL_dconic.x - (denom + 2 * b * b) * dL_dconic.y + a * b * dL_dconic.z);
> ```

Thanks for the answer! I checked the derivation again with your hint, and it comes out right!

**Comment by PanagiotisP** [comment]
Exactly as @Eku127 said, there is no "compensation". The various factors originate from the math derivation and, in the end, the gradients are computed correctly. I just want to shed light on another inconsistency/change in convention existing in the code that was a source of confusion for me.

In many cases, it is needed to pass a symmetric matrix from one function to another. To save up on space, instead of storing the full NxN matrix, only the upper triangular part is stored. That would make a 3 elements vector/struct for a 2x2 matrix and 6 elements for a 3x3. While in the forward pass, this doesn't create any confusion, in the backward pass, for partial derivative w.r.t. symmetric matrices, there is a semantic and practical difference whether the vector/struct contains the derivatives w.r.t. the matrix entries, or w.r.t. the different elements. Both are valid, mathematically, it's just that for the non-diagonal elements, the derivative is double the corresponding non-diagonal matrix entries.
As @Eku127 said, in the original point in question, the 0.5 factor comes from the fact that this vector/struct stores the derivatives w.r.t. the **matrix entries** (the one w.r.t. the **elements** would have the expected factor of 1 for the non-diagonal element, as you double it, but later on the equations would be different, as they are computed with matrices in mind).
However, in [other parts](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L212) of the code, in contrary to that first point, the vector/struct stores the derivative w.r.t. the elements, so the non-diagonal ones are doubled and this is taken into consideration in the derivation equations later on. For example, [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L308-L312) the non-diagonal entries are all halved, as the vector/struct contained the derivatives.

Hope that helped

**Comment by Ruyi-Zha** [comment]
I think both arguments make sense. If you consider `dL_dconic2D.y` as the derivative w.r.t. **matrix entry** (element in the first row, second column), then [0.5 factor](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L550) is correct and should be [*2](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L212) when you actually compute the derivative w.r.t. the element `dL_db`.  If you consider  `dL_dconic2D.y` as the derivative w.r.t. **element** (two matrix entries), then  [0.5 factor](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L550) should be 1 and there will be no [*2](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/backward.cu#L212) in the following part. Both ideas end up with the same solution.  I derive backpropagation in the second way, so I use the word 'compensate' to describe that.
 
 Great discussion btw :)
