### ISSUE TITLE
How to initialization with a random point cloud in my own datasets? 

### ISSUE THREAD

**Issue by fanzz1208** [graphdeco-inria/gaussian-splatting#618]
I saw in the paper that without SFM point cloud results, training can still be conducted. How should I proceed?

**Comment by jaco001** [comment]
https://github.com/graphdeco-inria/gaussian-splatting/issues/617#issuecomment-1897899487

**Comment by fanzz1208** [comment]
> [#617 (comment)](https://github.com/graphdeco-inria/gaussian-splatting/issues/617#issuecomment-1897899487)

When I delete a point cloud file, the code reports an error.
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/120933924/206adce5-51cb-433f-8887-2d15cd749bcd)

**Comment by jaco001** [comment]
You can make different input.ply (eg in the blender and export it) and replace it. Training can be stopped and restarted.

**Comment by prakashknaikade** [comment]
may be try empty ply file without any point

**Comment by pknmax** [comment]
may be try empty ply file without any point

**Comment by Snosixtyboo** [comment]
Hi, this is tricky because you would need to know the bounds of the scene to spawn random points in. However, if you DO know them, you could go ahead and simply replicate the behavior that is performed when loading the Blender Data in the ```dataset_readers.py```. Alternatively, you could generate a custom randomized ```points3D.ply``` and use that instead of the one that is created when the scene is first run.
