### ISSUE TITLE
Specular reflections rendering with transparency and the relation to sparse points size

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#63]
I have a question for the rendering appearance of specular reflections, and transparency in general.

It seems that specular reflections are handled by assigning them to the back side of the ellipsoids to create the view dependant reflections. We are seeing issues that if the gaussians are too large, the reflections shining through make the appearance of skin transparent.

We notice that the gaussians are larger on darker shaded areas and denser on better lit areas, and using a dense cloud with even distributing of points does not effect the outcome, in fact it doesn't make much difference of we use the same dense cloud across multiple different poses where the person has moved.
How close is the relation to the point cloud and the result, what is the purpose of using a sparse cloud it you can use a random cloud of points?

Can you suggest any settings to create a more unified size of gaussians or a limit on the largest size? we think if they are smaller the transparency issue should be reduced. 
Also any other settings to try in general based on human sized isolated subjects.

thankyou
Henry

**Comment by grgkopanas** [comment]
Hi,

we show in the paper that for bounded scenes like the nerf-synthetic dataset it is possible to start from a random dataset. So in the case of humans that you try probably the initial point cloud is not very important. 

One way to restrict the size of the gaussians is possible through reguralization, you would need to add an extra loss term that penalizes big gaussians, in that case I would personally penalize the total volume rather than the xyz extent such that you allow very thin ellipsoids to appear, since they have small volume, but not allow big gaussians that occupy a lot of space. 

If you want gaussians with uniform size you would need to penalize the distance of each gaussian from the average gaussian size, again I would focus on the volume rather than the individual xyz extents.

**Comment by henrypearce4D** [comment]
Are my assumptions correct that if if reduce the size of the gaussians and make them denser the transparency side effects should be improved.

Can the 'weighting' of guiding the gaussians to the point clod be increased? 

Also if this is the case that there are denser and more gaussians, would there be a way to lower the colour resolution per gaussian to make the scene less heavy?

**Comment by grgkopanas** [comment]
On Fri, Jul 28, 2023 at 10:01 AM henrypearce4D ***@***.***>
wrote:

> Are my assumptions correct that if if reduce the size of the gaussians and
> make them denser the transparency side effects should be improved.
>
I believe it can be the case but I am not 100% sure, the transparency can
be due to many factors, i.e if you have a dark object in front of a dark
background there it's not clear if the object is transparent and you can
see the background or the object is just dark.

I think this is something that someone will need to experiment with.


> Can the 'weighting' of guiding the gaussians to the point clod be
> increased?
>
This is not trivial in the current code base you would need to formulate it
in a mathematical way and add it to the loss here:
https://github.com/graphdeco-inria/gaussian-splatting/blob/main/train.py#L89


> Also if this is the case that there are denser and more gaussians, would
> there be a way to lower the colour resolution per gaussian to make the
> scene less heavy?
>
Each gaussian has a color component that is view dependent, the amount of
complexity in the view dependent effects defines that amount of parameters
per gaussian, the more diffuse the scene the more you can get away with
less parameters (there is a parameter for that called sh_degree) if you
have more gaussians and this is not related as far as i can tell.

**Comment by lxzbg** [comment]
> Hi,
> 
> we show in the paper that for bounded scenes like the nerf-synthetic dataset it is possible to start from a random dataset. So in the case of humans that you try probably the initial point cloud is not very important.
> 
> One way to restrict the size of the gaussians is possible through reguralization, you would need to add an extra loss term that penalizes big gaussians, in that case I would personally penalize the total volume rather than the xyz extent such that you allow very thin ellipsoids to appear, since they have small volume, but not allow big gaussians that occupy a lot of space.
> 
> If you want gaussians with uniform size you would need to penalize the distance of each gaussian from the average gaussian size, again I would focus on the volume rather than the individual xyz extents.

I tried regularizing the 3D Gaussian volume, but it didn't improve PSNR. Are you sure Gaussian regularization would help? My current understanding is that it just split a large Gaussian into multiple small Gaussians, the output model becomes larger, and there is almost no difference in rendering

**Comment by grgkopanas** [comment]
No I am not, this is hand wavy and its out of the scope of the paper so there are no quarantees, it would be considered and active area of research.

Best,
-gk

**Comment by prakashknaikade** [comment]
@lxzbg can you please share your implementation code/details?

**Comment by lxzbg** [comment]
> @lxzbg can you please share your implementation code/details?

I have tried regularizing the 3D Gaussian volume and the projected 2D Gaussian, but neither worked.Maybe I didn't implement it the right way. As the author mentioned in the paper that “As a consequence, our 𝛼-blending can be approximate in some configurations. However, these approximations become negligible as splats approach the size of individual pixels.”, I thought a smaller Gaussian would give a better approximation, but I don't get good results. You can also try some more. If there is any good news, I look forward to your reply.

**Comment by pknmax** [comment]
@grgkopanas 
> I believe it can be the case but I am not 100% sure, the transparency can be due to many factors, i.e if you have a dark object in front of a dark background there it's not clear if the object is transparent and you can see the background or the object is just dark. I think this is something that someone will need to experiment with.

I have a similar case:
I have planar object which turns dark for certain viewing direction and background is also dark,
and so during optimization those points get pruned, how we can deal with this case?
