### ISSUE TITLE
Loading colmap datasets with RGBA images

### ISSUE THREAD

**Issue by henrypearce4D** [graphdeco-inria/gaussian-splatting#64]
Hi,
I would like to know if loading colmap datasets with RGBA images is possible and how will training handle if the areas that have transparency are different in different images? Meaning, will areas that have transparency be treated as if the pixels are black or will they be treated like the images are cropped, and that area is not used as part of training at all? 

From what I can see, if say I have added a mask at the lower edge of an image to mask out the blur from poor depth of field, this is creating black bars in the data from those angles, yet for the synthetic nerf datasets those areas are treated as transparency, really I would want those areas to not influence the scene at all.

I think this is the section for the colmap camera loader in the dataset_readers.py;
https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/dataset_readers.py#L68
`def readColmapCameras(cam_extrinsics, cam_intrinsics, images_folder):`

And I think this is the section synthetic nerf datasets that has RGBA images.
https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/dataset_readers.py#L216
`def readNerfSyntheticInfo(path, white_background, eval, extension=".png"):`

The synthetic nerf reader has extra options there defining the background and extension, if this what informs trainign what to do with transparency? Are these options available for the colmap data reader, are they already implemented in some way?

**Comment by grgkopanas** [comment]
> Hi, I would like to know if loading colmap datasets with RGBA images is possible and how will training handle if the areas that have transparency are different in different images? Meaning, will areas that have transparency be treated as if the pixels are black or will they be treated like the images are cropped, and that area is not used as part of training at all?

Unfortunately, in the current code base we don't handle that.
https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/cameras.py#L44

Ideally, you would want to keep the gt_alpha_mask in a member variable of the class and then when calculating the loss, multiply the final rendering with the gt_alpha_mask.

Should be a few lines of code.

> The synthetic nerf reader has extra options there defining the background and extension, if this what informs trainign what to do with transparency? Are these options available for the colmap data reader, are they already implemented in some way?

That doesn't have to do with transparency we actually don't handle the transparency as a gt_alpha_mask in the blender dataset because we need to assume only RGB as input to make a fair comparison with other algorithms.

**Comment by henrypearce4D** [comment]
As always thanks for the info!

**Comment by Yang-Xijie** [comment]
I'm rather comfused with the process to load images and train from nerf-blender-synthetic dataset.

When creating a new `Camera` instance, `loadCam()` in utils/camera_utils.py will be called:

https://github.com/graphdeco-inria/gaussian-splatting/blob/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2/utils/camera_utils.py#L41-L47

First, the `resized_image_rgb.shape` looks like `torch.Size([3, 800, 800])` when training using nerf-blender-synthetic dataset. So I think `resized_image_rgb.shape[1]` should be `resized_image_rgb.shape[0]`? So, the `loaded_mask` (`camera.gt_alpha_mask`) will always be `None`?

Secondly, the `cam_info.image` comes originally from `image = Image.fromarray(np.array(arr*255.0, dtype=np.byte), "RGB")`, which means `cam_info.image` will never have RGBA 4 channels:

https://github.com/graphdeco-inria/gaussian-splatting/blob/ea68bdf29c3b11d1a7ec2e5a11b1af2c266bd7f2/scene/dataset_readers.py#L179-L219

To verify, I add some `print()` statements when running `train.py` with lego data in  nerf-blender-synthetic dataset. The `resized_image_rgb.shape[0]` is always `3`. And the `camera.gt_alpha_mask` is always `None`.

Is this an expected behaviour because you said "in the current code base we don't handle that"? @grgkopanas

**Comment by grgkopanas** [comment]
For the blender dataset seems to me that we flatten the image at line 209 and blend a background color given an alpha mask. 

But I think even if we load the alpha mask properly  then if I recall correctly I believe that we don't use the mask anywhere in the code base.

But I didn't have time to double check the last statement

**Comment by applepieiris** [comment]
> > Hi, I would like to know if loading colmap datasets with RGBA images is possible and how will training handle if the areas that have transparency are different in different images? Meaning, will areas that have transparency be treated as if the pixels are black or will they be treated like the images are cropped, and that area is not used as part of training at all?
> 
> Unfortunately, in the current code base we don't handle that. https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/cameras.py#L44
> 
> Ideally, you would want to keep the gt_alpha_mask in a member variable of the class and then when calculating the loss, multiply the final rendering with the gt_alpha_mask.
> 
> Should be a few lines of code.
> 
> > The synthetic nerf reader has extra options there defining the background and extension, if this what informs trainign what to do with transparency? Are these options available for the colmap data reader, are they already implemented in some way?
> 
> That doesn't have to do with transparency we actually don't handle the transparency as a gt_alpha_mask in the blender dataset because we need to assume only RGB as input to make a fair comparison with other algorithms.

Is there any updating on this feature? I see current code only calculates the alpha_mask with the rendering image but not with origianl_image(gt_image):
`gt_image = resized_image_rgb[:3, ...]
self.original_image = gt_image.clamp(0.0, 1.0).to(self.data_device)
`

`gt_image = viewpoint_cam.original_image.cuda()
Ll1 = l1_loss(image, gt_image)
`
