### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [graphdeco-inria/gaussian-splatting#663]
Hi,
With the rise of Sora and other projects that depend on Gaussian Splatting, are there any plans to switch to an open source license? Switching to an open source license would help support the open source community and promote development of open source projects.
Thanks!

**Comment by Snosixtyboo** [comment]
Hi,

I am not giving legal advice, but as far as I know the license (please check with an expert for your specific purposes), you are free to do "open-source" development with this code (after all, this code is open-source, too), as long as you make sure you include its original license. It does not restrict experimental, non-profit, or academic endeavors. It is only when you are trying to **monetize** this code or the outputs of it that the license affects your ability to use it.

hth,
Bernhard

**Comment by fakerybakery** [comment]
Thank you! Unfortunately according to the OSI OSD, I'm pretty sire NC licenses don't count as open source

**Comment by Snosixtyboo** [comment]
> Thank you! Unfortunately according to the OSI OSD, I'm pretty sire NC licenses don't count as open source

You're right, I had a wrong understanding of the exact terms. But there are no plans to change the license in response to the release of Sora or other projects.

**Comment by fakerybakery** [comment]
OK, thank you!

**Comment by SharkWipf** [comment]
I would like to add another voice/perspective here, without opening a new issue.
Gaussian splatting has gotten really big in a short time, which is great. Lots of research is being done, and lots of papers are being published.
Most of the gaussian splatting whitepapers being released base themselves on the Inria Gaussian Splatting repo and are thus automatically bound to the Gaussian Splatting license, thus restricting commercial use. 
Nothing inherently wrong with that of course.

One perspective that isn't directly obvious however, is that it is also suppressing non-commercial use, and quite heavily so.
Any project that _isn't_ based on Inria's code, any project that _doesn't_ use the Gaussian Splatting license, cannot use any of the Gaussian Splatting licensed code. The license is inherently incompatible with any other software license, commercial or not.
As long as this license is used, no other external project can implement any of the code from Inria, nor any of the whitepapers that build on it, commercial or not.

For example, [Nerfstudio](https://github.com/nerfstudio-project/nerfstudio), or more specifically its [Gsplat](https://github.com/nerfstudio-project/gsplat) subproject, a completely from-scratch open source implementation of gaussian splatting, has more than once completely had to rewrite whitepaper projects in order to implement the highly desirable features, and many features never get implemented because there simply isn't enough manpower to keep rewriting projects. The license is actively stifling open source project development in this way.

Every time someone posts a new project in the research channel of the Nerfstudio discord, the first reaction is "Ugh, Inria".
I can't imagine that is the intention you had choosing the license.

Of course, it is your right to use whatever license you want on your project, but I wanted to highlight a different view that you might not have realized.
