### ISSUE TITLE
Issue of Loading Gaussians for Fine-Tuning.

### ISSUE THREAD

**Issue by ZhiyeTang** [graphdeco-inria/gaussian-splatting#807]
Noticed that in `scene/__init__.py`, the class `Scene` receives a variable `load_iteration`, which seems to support fine-tuning. However, in the following lines:

```{Python}
if self.loaded_iter:
            self.gaussians.load_ply(os.path.join(self.model_path,
                                                           "point_cloud",
                                                           "iteration_" + str(self.loaded_iter),
                                                           "point_cloud.ply"))
        else:
            self.gaussians.create_from_pcd(scene_info.point_cloud, self.cameras_extent)
```
the `load_ply()` function does not set the variable `gaussians.max_radii2D` from the loaded `ply` file, making further training impossible. The question is, **how can I set this variable properly?** Seems that it cannot be simply parsed from the trained `ply` files.

**Comment by ZhiyeTang** [comment]
Is simply setting `gaussians.max_radii` as all-zero tensors like in `create_from_pcd()`, as
```{Python}
self.max_radii2D = torch.zeros((self.get_xyz.shape[0]), device="cuda")
```
feasible? I'm not sure.

**Comment by hariharan1412** [comment]
From my knowledge, I can say that 

''' self.max_radii2D '''

are used when projecting 3D gaussians to a 2D surface. Yes,  ''' max_radii2D ``` is set to be all zero before passing through the projection, and once rasterization is done, it will again be set to be zero. It is highly likely this variable is set to be zero only for the optimization purpose.  How ever you can change this behaviour by modifying the CUDA code.

**Comment by ZhiyeTang** [comment]
> From my knowledge, I can say that 
> 
> `self.max_radii2D`
> 
> are used when projecting 3D gaussians to a 2D surface. Yes,  `max_radii2D` is set to be all zero before passing through the projection, and once rasterization is done, it will again be set to be zero. It is highly likely this variable is set to be zero only for the optimization purpose.  How ever you can change this behaviour by modifying the CUDA code.

Thank you. I've recognized that the correct way to do fine-tuning is to save checkpoints at certain iterations and retrain by loading saved checkpoints. This issue will be closed. Thanks a lot again.

**Comment by Dumeowmeow** [comment]
> > From my knowledge, I can say that 
> > `self.max_radii2D`
> > are used when projecting 3D gaussians to a 2D surface. Yes,  `max_radii2D` is set to be all zero before passing through the projection, and once rasterization is done, it will again be set to be zero. It is highly likely this variable is set to be zero only for the optimization purpose.  How ever you can change this behaviour by modifying the CUDA code.
> 
> Thank you. I've recognized that the correct way to do fine-tuning is to save checkpoints at certain iterations and retrain by loading saved checkpoints. This issue will be closed. Thanks a lot again.

How to load gaussians from checkpoint?

**Comment by JianxiangL** [comment]
Hello, I'm also struggling with this issue. When I use the load_ply function to reload a trained point_cloud.ply for retraining, I notice that the render images  with Gaussians splattting (which should be clear) appear very blurry. Have you encountered similar problems before, or could you share any relevant experiences? I would greatly appreciate any insights or advice you can share! 拜托！

**Comment by ZhiyeTang** [comment]
Do not use the load_ply function. Try loading a checkpoint that was saved previously. @JianxiangL

**Comment by JianxiangL** [comment]
> Do not use the load_ply function. Try loading a checkpoint that was saved previously. [@JianxiangL](https://github.com/JianxiangL)

It turned out that the code version I was using was outdated, and I hadn't saved any checkpoints before. Thank you so much for your help！！！

**Comment by ZhiyeTang** [comment]
Have you ever tried running "render.py" to render the trained 3DGS point cloud? It will also call the `load_ply` function to load a ply file as Gaussians. Do the rendered results have a similar L1 and SSIM as in the training pipeline? @JianxiangL

**Comment by JianxiangL** [comment]
Sorry&nbsp;for&nbsp;the&nbsp;late&nbsp;reply.&nbsp;Regarding&nbsp;the&nbsp;render.py&nbsp;you&nbsp;mentioned,&nbsp;I&nbsp;tried&nbsp;it&nbsp;and&nbsp;found&nbsp;that&nbsp;render.py&nbsp;can&nbsp;produce&nbsp;very&nbsp;sharp&nbsp;images,&nbsp;but&nbsp;the&nbsp;rendering&nbsp;from&nbsp;train.py&nbsp;is&nbsp;still&nbsp;blurry...&nbsp;It&nbsp;feels&nbsp;like&nbsp;we're&nbsp;on&nbsp;the&nbsp;cusp&nbsp;of&nbsp;solving&nbsp;it.&nbsp;Since&nbsp;render&nbsp;and&nbsp;train&nbsp;should&nbsp;share&nbsp;similar&nbsp;logic,&nbsp;I'll&nbsp;proceed&nbsp;to&nbsp;compare&nbsp;the&nbsp;differences&nbsp;between&nbsp;them&nbsp;next.&nbsp;


见香
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TANG ***@***.***&gt;; 
发送时间: 2025年5月12日(星期一) 中午1:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [graphdeco-inria/gaussian-splatting] Issue of Loading Gaussians for Fine-Tuning. (Issue #807)












唐志业留下评论（graphdeco-inria/高斯溅射#807）

您是否尝试过运行"render.py"来渲染经过训练的3DGS点云？它还将呼吁加载层函数将层文件加载为高斯文件。渲染结果的L1和SSIM是否与培训管道中的类似？@剑翔L

-
直接回复这封邮件，在GitHub上查看它，或者取消订阅.
***@***.*** &gt;
