### ISSUE TITLE
How the gradient of GaussianRasterization is passed to viewpoint_camera？

### ISSUE THREAD

**Issue by Bin-ze** [graphdeco-inria/gaussian-splatting#84]
I want to add pose optimization on the basis of this algorithm, but I found that GaussianRasterization will not pass the gradient to the viewpoint_camera, how can I do it?

**Comment by Snosixtyboo** [comment]
Since the rasterizer is a custom CUDA extension, you would have to derive and compute the gradients w.r.t. the camera in CUDA code and then return them. Depending on your familiarity with CUDA, I am afraid this can be a challenging task. But if you want to attempt it, the methods ```preprocess``` and ```computeCov2D``` are the ones you want to look at and where you would collect the gradients for the camera in the backward.

Alternatively, you could try to do any CUDA steps that the camera is involved in through pytorch (computing the 2D covariance matrix, projection of means). That would make things quite a bit slower however, but you would not need to derive camera gradients yourself.

I'm afraid that neither option is trivial, both will need a good amount of programming and math skills.

Hth,
Bernhard

**Comment by kuldeepbrd1** [comment]
Hi @Snosixtyboo 

Thanks for your comment and this great work.

I tried adding backward gradients of the loss explicitly w.r.t the camera pose using an over-parameterized SE(3) pose matrix. 
Would greatly appreciate it, if you could check whether this makes sense.

In `__global__ void computeCov2DCUDA(...)`:

```c
        
         // ---------------- Gradients w.r.t Tcw ------------
	// Gradients due to 2D covariance : 1st gradient portion from 2D covariance -> 3D means(t))
	
        // flattened_3x4_pose = {r00, r01, r02, r10, r11, r12,  r20, r21, r22, t0, t1, t2}
	// dL/dTcw = dL/dcov_c * dcov_c/dW * dW/dTcw
	
	// Loss w.r.t W:   dL/dW = dL/dT *dT/dW
	// dL/dW = J^T * dL/dT
	float dL_dW00 = J[0][0] * dL_dT00 + J[1][0] * dL_dT10;
	float dL_dW10 = J[0][0] * dL_dT01 + J[1][0] * dL_dT11;
	float dL_dW20 = J[0][0] * dL_dT02 + J[1][0] * dL_dT12;
	float dL_dW01 = J[0][1] * dL_dT00 + J[1][1] * dL_dT10;
	float dL_dW11 = J[0][1] * dL_dT01 + J[1][1] * dL_dT11;
	float dL_dW21 = J[0][1] * dL_dT02 + J[1][1] * dL_dT12;
	float dL_dW02 = J[0][2] * dL_dT00 + J[1][2] * dL_dT10;
	float dL_dW12 = J[0][2] * dL_dT01 + J[1][2] * dL_dT11;
	float dL_dW22 = J[0][2] * dL_dT02 + J[1][2] * dL_dT12;
	
	// Loss w.r.t Tcw elements
	dL_dTcw[0] += dL_dtx * t.x + dL_dW00;
	dL_dTcw[1] += dL_dtx * t.y + dL_dW10;
	dL_dTcw[2] += dL_dtx * t.z + dL_dW20;
	dL_dTcw[3] += dL_dty * t.x + dL_dW01;
	dL_dTcw[4] += dL_dty * t.y + dL_dW11;
	dL_dTcw[5] += dL_dty * t.z + dL_dW21;
	dL_dTcw[6] += dL_dtz * t.x + dL_dW02;
	dL_dTcw[7] += dL_dtz * t.y + dL_dW12;
	dL_dTcw[8] += dL_dtz * t.z + dL_dW22;
	dL_dTcw[9] += dL_dtx;
	dL_dTcw[10] += dL_dty;
	dL_dTcw[11] += dL_dtz;
```

And in `__global__ void preprocessCUDA()`:
```c
        // ---------------- Gradients w.r.t Tcw ------------
	//  Gradients for 3x4 elements due to 2D means
	// (2nd gradient portion from 2D means -> 3D means(t))
	// flattened_3x4_pose = {r00, r01, r02, r10, r11, r12,  r20, r21, r22, t0, t1, t2}
	dL_dTcw[0] += dL_dmean.x * t.x;
	dL_dTcw[1] += dL_dmean.x * t.y;
	dL_dTcw[2] += dL_dmean.x * t.z;
	dL_dTcw[3] += dL_dmean.y * t.x;
	dL_dTcw[4] += dL_dmean.y * t.y;
	dL_dTcw[5] += dL_dmean.y * t.z;
	dL_dTcw[6] += dL_dmean.z * t.x;
	dL_dTcw[7] += dL_dmean.z * t.y;
	dL_dTcw[8] += dL_dmean.z * t.z;
	dL_dTcw[9] += dL_dmean.x;
	dL_dTcw[10] += dL_dmean.y;
	dL_dTcw[11] += dL_dmean.z;
```

PS: I would much like to do this on se3 logmap representation later. But this is easier for the moment.
