### ISSUE TITLE
Can't save camera and video in SIBR_gaussianViewer_app on Windows 11

### ISSUE THREAD

**Issue by wzy-99** [graphdeco-inria/gaussian-splatting#86]
Hi,

I am unable to save camera and video in SIBR_gaussianViewer_app on Windows 11. I am using the compiled binary file.

The command I am running is as follows:

```powershell
PS D:\wzy\viewers\bin> ./SIBR_gaussianViewer_app.exe --s "D:\wsl\data\ship" --m "D:\wsl\output\gaussian-splatting\ship" --appPath "D:\wzy\viewers\output"
```

When I click the "Save camera (bin)" and "Save key cameras" buttons, no files are generated.
When I select the "Save video (from playing)" and "Save frame (from playing)" options, and then record, stop, and play, no files are generated.

In addition, I have also found the following problems:

1. When I click the "Capture" menu in the upper left corner and select "Set export directory...", nothing happens (no pop-up window).
2. When I click the "Capture" menu in the upper left corner and select "Point view/Top view", a screenshot can be saved to the current "screenshots" subfolder.

I would appreciate it if you could help me to troubleshoot this issue.

Thank you for your time.

**Comment by Snosixtyboo** [comment]
Hi,

sorry to hear that this is producing issues for you. This seems like a problem with SIBR, but I don't know what is causing this since it's working fine on my own Windows 11. It has to be somehow related to a library called ```nativefiledialog```, but how exactly, I don't know... maybe I can make a flag that avoids nativefiledialog and stores everything with a specified name (that seems to work for you when you do screenshots it seems?), but it might take a while and is not top priority

**Comment by wzy-99** [comment]
Thank you for your response. I appreciate you taking the time to look into my issue.

I understand that you said this may not be the highest priority, so I won't push it. I just wanted to let you know that I'm experiencing this problem and I hope you'll consider fixing it.

Thank you again for your help.

**Comment by wzy-99** [comment]
I was able to build the SIBR source code on Windows 11 using the latest fossa_compatibility branch a125ab83425ab857925a18d613ba3691b517a1d0. The built SIBR_gaussianViewer_app can now save videos.

Thank you for your help.
