### ISSUE TITLE
Why the output point cloud not align with the input sparse point cloud?

### ISSUE THREAD

**Issue by sumai-1998** [graphdeco-inria/gaussian-splatting#87]
The two point clouds are at ./output-train/input.ply(green) and  ./output-train/point_cloud/iteration_30000/point_cloud.ply(red), I use the 'train' data, and the 'train' in these two point clouds not align as show in the figure below
![input_and_30000iter](https://github.com/graphdeco-inria/gaussian-splatting/assets/53565345/c17c71c4-6ba5-4faa-bedf-26cf7c19bb80)
both point clouds are down sampled to 20,000 vertices for better visualization. 
input sparse point cloud from colmap
![input-point-cloud](https://github.com/graphdeco-inria/gaussian-splatting/assets/53565345/a073bc2b-a342-4332-869d-af6f050a8074)

generated point cloud at 30000 iterations
![30000iter-point-cloud](https://github.com/graphdeco-inria/gaussian-splatting/assets/53565345/6f21f13f-ffd6-46cb-b706-87fb5b136458)

**Comment by Snosixtyboo** [comment]
Hi,

can you make it a little clearer which part of the train this is and how big the discrepancy is? I just looked at the full data set in MeshLab, afaict the Gaussians seem to align quite well with the input points. 

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/40643808/2ba3d005-9a2d-4a01-959a-86dd24c50c7e)

Couple of things:

- there is nothing forcing the final gaussians to align with the input, they are free to move around
- they will do whatever they need to try and fit the appearance in the photographs
- the initial sfm points are always points on the surface of objects. A volumetric Gaussian MAY instead move towards the interior of an object, since it has non-zero extent.

**Comment by Snosixtyboo** [comment]
the second example seems to compare ```input``` and ```point_cloud```, so it looks like you are comparing the outputs of our program directly. What does this give for the train? Is it possible that the subsampling that creating the subsampling you show for the train somehow causes misalignment?

**Comment by Snosixtyboo** [comment]
Hi,

I ran it now from scratch with the same parameters you use and the result is here

https://filesender.renater.fr/?s=download&token=07e1caee-c02c-4b3c-ae14-bd2850401b2d

Again, they seem to align for me

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/40643808/679cc978-4442-478d-a0cc-066e3756f0a6)

We also have pretrained models, so the inputs and final point clouds for each scene should be available for you.

**Comment by Snosixtyboo** [comment]
Hi,

Colmap is free to choose scene axes arbitrarily, as long as the cameras are aligned relative to each other. It starts from nothing except photographs, it has no idea about real-world coordinates. So there is also no requirement (and no incentive) for it to reproducibly pick the same axes for its reconstruction.
